import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { getUserProfile, deleteUserAccount } from '../services/api'; 
import toast from 'react-hot-toast'; 
import { jsPDF } from "jspdf";

const Dashboard = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);
  const [profile, setProfile] = useState(null);
  const [bmi, setBmi] = useState(null);
  const [loading, setLoading] = useState(true);
  

  const [profilePic, setProfilePic] = useState(localStorage.getItem("profilePic") || null);
  const fileInputRef = useRef(null); 

 
 const [theme, setTheme] = useState(localStorage.getItem("theme") || "dark");

  useEffect(() => {
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("theme", theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(theme === "light" ? "dark" : "light");
  };

  const handleImageUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setProfilePic(reader.result);
        localStorage.setItem("profilePic", reader.result);
        toast.success("Profile Photo Updated! 📸");
      };
      reader.readAsDataURL(file);
    }
  };

  const dietPlans = {
    "Weight Loss": { 
      breakfast: [
        "🥣 Oatmeal (1 cup) with Water/Skim Milk",
        "🍎 1 Sliced Apple & Walnuts (4-5)",
        "☕ Green Tea (No Sugar)"
      ],
      lunch: [
        "🥗 Grilled Chicken Breast (150g) or Tofu",
        "🍛 Brown Rice (1/2 cup) + Dal (1 bowl)",
        "🥒 Cucumber & Tomato Salad"
      ],
      snack: [
        "🥕 Carrot Sticks with Hummus",
        "🍊 1 Orange or Grapefruit"
      ],
      dinner: [
        "🍲 Vegetable Soup (1 big bowl)",
        "🥦 Boiled Broccoli & 2 Egg Whites",
        "🍞 No Roti/Rice at night (Low Carb)"
      ]
    },
    "Muscle Gain": { 
      breakfast: [
        "🍳 4 Boiled Eggs (2 Whole, 2 Whites)",
        "🍞 2 Whole Wheat Toast + Peanut Butter",
        "🍌 1 Banana Shake with Whey Protein"
      ],
      lunch: [
        "🍗 Chicken Curry / Fish Fry (200g)",
        "🍛 White Rice (2 cups) + Dal Fry",
        "🥛 Curd / Yogurt (1 cup)"
      ],
      snack: [
        "🥪 Paneer Sandwich / Chicken Roll",
        "🥜 Handful of Almonds & Cashews"
      ],
      dinner: [
        "🥙 3 Chapatis with Ghee",
        "🥘 Mixed Veg / Paneer Butter Masala",
        "🥛 Warm Milk with Turmeric"
      ]
    },
    "Maintenance": { 
      breakfast: [
        "🥘 Idli (3) or Dosa (1) with Sambar",
        "☕ Filter Coffee / Tea (Low Sugar)"
      ],
      lunch: [
        "🍛 Rice (1 cup) + 2 Rotis",
        "🍲 Seasonal Vegetable Curry + Dal",
        "🥗 Small Salad Bowl"
      ],
      snack: [
        "🌽 Corn / Sweet Potato (Boiled)",
        "🥜 Roasted Peanuts / Chana"
      ],
      dinner: [
        "🥙 2 Phulkas (Roti) + Jeera Aloo",
        "🥣 Lentil Soup (Dal)",
        "🍎 Fruit Salad"
      ]
    }
  };
  const downloadPDF = () => {
    const doc = new jsPDF();
    const plan = dietPlans[profile.goal];

   
    doc.setFontSize(22);
    doc.setTextColor(40, 167, 69);
    doc.text("NutriHealth Advisor", 20, 20);
    
  
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Name: ${user.name}`, 20, 30);
    doc.text(`Goal: ${profile.goal}`, 20, 36);
    doc.text(`Current BMI: ${bmi}`, 20, 42);

  
    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);

    // 4. Diet Plan Content
    let yPos = 60;
    
    // Helper to print sections
    const printSection = (title, items) => {
      doc.setFontSize(16);
      doc.setTextColor(0, 102, 204); // Blue for titles
      doc.text(title, 20, yPos);
      yPos += 8;
      
      doc.setFontSize(12);
      doc.setTextColor(50, 50, 50); // Dark Gray for items
      items.forEach((item) => {
        doc.text(`• ${item}`, 25, yPos);
        yPos += 7;
      });
      yPos += 10; // Space between sections
    };

    if (plan) {
      printSection("Breakfast ☀️", plan.breakfast);
      printSection("Lunch 🍛", plan.lunch);
      printSection("Evening Snack 🍎", plan.snack);
      printSection("Dinner 🌙", plan.dinner);
    }

    // 5. Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by NutriHealth Advisor App", 20, 280);

    // 6. Save File
    doc.save(`${user.name}_Diet_Plan.pdf`);
    toast.success("PDF Downloaded Successfully! 📄");
  };

  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    const token = localStorage.getItem('token');
    if (!token || !storedUser) {
      navigate('/login');
    } else {
      setUser(JSON.parse(storedUser));
      fetchProfile();
    }
  }, [navigate]);

  const fetchProfile = async () => {
    try {
      const { data } = await getUserProfile();
      setProfile(data);
      if (data.height && data.weight) {
        const h = data.height / 100;
        setBmi((data.weight / (h * h)).toFixed(1));
      }
      setLoading(false);
    } catch (error) {
      console.log("No profile found");
      setLoading(false);
    }
  };

  const handleLogout = () => {
    toast.success("Logged out successfully!");
    localStorage.clear();
    navigate('/login');
  };

  const performDelete = async (toastId) => {
    toast.dismiss(toastId); 
    const loadingToast = toast.loading("Deleting account permanently...");
    try {
      await deleteUserAccount();
      toast.dismiss(loadingToast);
      toast.success("Account Deleted. Goodbye! 👋");
      localStorage.clear();
      setTimeout(() => navigate('/register'), 1000);
    } catch (err) {
      toast.dismiss(loadingToast);
      toast.error("Failed to delete account.");
    }
  };

  const confirmDeleteAccount = () => {
    toast((t) => (
      <div className="flex flex-col items-center gap-2 p-2">
        <p className="font-bold text-gray-800 text-sm">⚠️ Permanently delete your account?</p>
        <div className="flex gap-3 mt-2">
          <button onClick={() => toast.dismiss(t.id)} className="px-3 py-1 bg-gray-200 text-gray-700 rounded-lg text-sm font-bold hover:bg-gray-300">Cancel</button>
          <button onClick={() => performDelete(t.id)} className="px-3 py-1 bg-red-500 text-white rounded-lg text-sm font-bold hover:bg-red-600">Yes, Delete</button>
        </div>
      </div>
    ));
  };

  const getBMIColor = () => {
    if (bmi < 18.5) return "text-yellow-500";
    if (bmi < 24.9) return "text-emerald-500";
    return "text-red-500";
  };

  return (
    <div className="min-h-screen transition-colors duration-500 font-sans
      bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50 
      dark:from-gray-900 dark:via-gray-900 dark:to-black">
      
      {/* NAVBAR */}
      <nav className="sticky top-4 z-50 flex justify-between items-center 
        bg-white/80 dark:bg-gray-800/80 backdrop-blur-md p-4 rounded-2xl shadow-lg border border-white/50 dark:border-gray-700 max-w-6xl mx-auto">
        
        <h1 className="text-2xl font-extrabold bg-gradient-to-r from-emerald-600 to-teal-500 bg-clip-text text-transparent">
          NutriHealth Advisor
        </h1>
        
        <div className="flex items-center gap-4">
          <button onClick={toggleTheme} className="p-2 rounded-full bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-yellow-400 hover:scale-110 transition-transform">
            {theme === "light" ? "🌙" : "☀️"}
          </button>

          <div className="hidden md:flex items-center gap-2">
            {profilePic ? (
              <img src={profilePic} alt="Profile" className="w-8 h-8 rounded-full border border-emerald-500 object-cover" />
            ) : (
              <div className="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center font-bold text-xs">
                {user?.name?.charAt(0).toUpperCase()}
              </div>
            )}
            <span className="font-semibold text-gray-700 dark:text-gray-200">Hi, {user?.name}</span>
          </div>
          
          <button onClick={handleLogout} className="bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-200 px-4 py-2 rounded-full font-bold text-sm hover:bg-gray-200 dark:hover:bg-gray-600 transition">
            Logout
          </button>
          
          <button onClick={confirmDeleteAccount} className="bg-red-50 dark:bg-red-900/20 text-red-500 px-4 py-2 rounded-full font-bold text-sm border border-red-100 dark:border-red-900 hover:bg-red-500 hover:text-white transition-all">
            Delete Account
          </button>
        </div>
      </nav>

      <div className="max-w-6xl mx-auto mt-10 animate-fade-in pb-10">
        
        {loading ? (
          <div className="text-center mt-20 animate-pulse"><h2 className="text-2xl text-gray-400 font-medium">Loading health data...</h2></div>
        ) : profile ? (
          <div className="space-y-10 px-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              
              {/* BMI Card */}
              <div className="bg-white dark:bg-gray-800 p-8 rounded-3xl shadow-xl border border-emerald-100 dark:border-gray-700 text-center hover:-translate-y-1 transition-transform duration-300">
                <h3 className="text-xl font-bold text-gray-500 dark:text-gray-400 uppercase">Your BMI Score</h3>
                <p className={`text-7xl font-black ${getBMIColor()} my-6 drop-shadow-sm`}>{bmi}</p>
                <span className={`px-4 py-1 rounded-full text-white font-bold ${bmi < 18.5 ? "bg-yellow-400" : bmi < 24.9 ? "bg-emerald-500" : "bg-red-500"}`}>
                  {bmi < 18.5 ? "Underweight" : bmi < 24.9 ? "Healthy" : "Overweight"}
                </span>
              </div>
              
              {/* Profile Card */}
              <div className="bg-gradient-to-br from-emerald-600 to-teal-700 dark:from-emerald-800 dark:to-teal-900 p-8 rounded-3xl shadow-xl text-white relative overflow-hidden hover:-translate-y-1 transition-transform duration-300">
                <div className="flex justify-between items-start mb-6 border-b border-white/20 pb-4">
                  <h3 className="text-xl font-bold">Your Profile</h3>
                  <div className="relative group cursor-pointer" onClick={() => fileInputRef.current.click()}>
                    {profilePic ? (
                      <img src={profilePic} alt="Profile" className="w-16 h-16 rounded-full border-2 border-white object-cover shadow-md group-hover:opacity-80 transition" />
                    ) : (
                      <div className="w-16 h-16 rounded-full bg-white/20 flex items-center justify-center border-2 border-white/50 text-2xl font-bold">
                        {user?.name?.charAt(0).toUpperCase()}
                      </div>
                    )}
                    <div className="absolute inset-0 flex items-center justify-center bg-black/30 rounded-full opacity-0 group-hover:opacity-100 transition">
                      <span className="text-xs font-bold">Edit</span>
                    </div>
                  </div>
                  <input type="file" ref={fileInputRef} onChange={handleImageUpload} className="hidden" accept="image/*"/>
                </div>

                <div className="grid grid-cols-2 gap-6 text-lg">
                  <div><p className="text-emerald-100 text-sm">Goal</p><p className="font-bold">{profile.goal}</p></div>
                  <div><p className="text-emerald-100 text-sm">Weight</p><p className="font-bold">{profile.weight} kg</p></div>
                  <div><p className="text-emerald-100 text-sm">Height</p><p className="font-bold">{profile.height} cm</p></div>
                  <div><p className="text-emerald-100 text-sm">Age</p><p className="font-bold">{profile.age} yrs</p></div>
                </div>
                <button onClick={() => navigate('/profile-setup')} className="mt-8 w-full bg-white text-emerald-700 dark:text-emerald-900 py-3 rounded-xl font-bold hover:bg-emerald-50 transition-colors shadow-lg">Edit Details ✏️</button>
              </div>
            </div>

            {/* Diet Plan Section */}
            <div className="bg-white/60 dark:bg-gray-800/60 backdrop-blur-sm p-8 rounded-3xl border border-white dark:border-gray-700 shadow-lg">
              <div className="flex flex-col md:flex-row justify-between items-center mb-8 gap-4">
                <h2 className="text-3xl font-extrabold text-gray-800 dark:text-white">Recommended Diet 🥗</h2>
                
                {/* PDF DOWNLOAD BUTTON */}
                <button 
                  onClick={downloadPDF} 
                  className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-6 rounded-full shadow-lg transform hover:scale-105 transition-all"
                >
                  Download PDF 📥
                </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                {['breakfast', 'lunch', 'snack', 'dinner'].map((type) => (
                  <div key={type} className="p-6 rounded-2xl bg-white dark:bg-gray-700 border border-gray-100 dark:border-gray-600 shadow-sm hover:shadow-xl hover:scale-105 transition-all duration-300">
                    <h4 className="font-bold capitalize mb-4 text-emerald-600 dark:text-emerald-400 text-xl border-b dark:border-gray-600 pb-2">{type}</h4>
                    
                    {/* Render List Items */}
                    <ul className="space-y-2">
                      {dietPlans[profile.goal]?.[type]?.map((item, index) => (
                        <li key={index} className="text-gray-600 dark:text-gray-300 text-sm font-medium flex items-start gap-2">
                          <span>•</span> {item}
                        </li>
                      ))}
                    </ul>

                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center mt-20 p-10 bg-white/80 dark:bg-gray-800/80 backdrop-blur-md rounded-3xl shadow-xl border border-white/50 dark:border-gray-700 max-w-2xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-700 dark:text-white mb-4">Welcome! 🌱</h2>
            <p className="text-lg text-gray-500 dark:text-gray-400 mb-8">Setup your profile to get your Diet Plan.</p>
            <button onClick={() => navigate('/profile-setup')} className="bg-gradient-to-r from-emerald-500 to-teal-600 text-white px-8 py-4 rounded-full font-bold text-lg shadow-lg hover:scale-105 transition">
              Complete Profile Now 🚀
            </button>
          </div>
        )}
      </div>
      <footer className="mt-10 py-6 text-center text-gray-500 dark:text-gray-400 text-sm font-medium bg-white/50 dark:bg-gray-800/50 backdrop-blur-sm border-t border-gray-100 dark:border-gray-800">
        <p>
          Designed & Developed with <span className="text-red-500 animate-pulse">❤️</span> by <span className="text-emerald-600 dark:text-emerald-400 font-bold">Avinash & Team</span>
        </p>
        <p className="text-xs mt-1 opacity-70">© 2025 NutriHealth Advisor. All Rights Reserved.</p>
      </footer>
    </div>
  );
};

export default Dashboard;